version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build Phase
  build:
    commands:
      - echo Build Phase
  post_build:
    commands:
      - echo Post Build Phase
artifacts:
  files:
    - target/spring-boot-hello-world.jar
